### ISSUE TITLE
periods in name break odgibuild logic

### ISSUE THREAD

**Issue by dbrami** [nf-core/pangenome#41] opened 2021-02-21 17:33 UTC
Hi,
I've paired down my test data set to fail fast. 
Here's the first error I could troubleshoot by changing naming convention
## Description of the bug

Input file names:
```bash
788K -rw-rw-r-- 1 ubuntu ubuntu 785K Feb 21 17:12 ncbi200.01.fasta.gz
784K -rw-rw-r-- 1 ubuntu ubuntu 783K Feb 21 17:12 ncbi200.00.fasta.gz
```
Steps to reproduce the behaviour:
`nextflow run nf-core/pangenome -r dev -profile docker --input 'ncbi200.*.fasta.gz' -c nfcore_ec2.config`

```bash
(pangenomics) ubuntu@ip-172-31-29-49:~/covid19/1k$ nextflow run nf-core/pangenome -r dev -profile docker --input 'ncbi200.*.fasta.gz' -c nfcore_ec2.config
N E X T F L O W  ~  version 20.10.0
Launching `nf-core/pangenome` [adoring_torricelli] - revision: 2652c2871a [dev]
----------------------------------------------------
                                        ,--./,-.
        ___     __   __   __   ___     /,-._.--~'
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                        `._,._,'
  nf-core/pangenome v1.0dev
----------------------------------------------------
executor >  local (5)
executor >  local (5)
executor >  local (5)
[0f/1de79e] process > edyeet (2)   [100%] 2 of 2 ✔
executor >  local (5)
[0f/1de79e] process > edyeet (2)   [100%] 2 of 2 ✔
[40/ac9ff7] process > seqwish (2)  [100%] 2 of 2 ✔
[a4/d139b3] process > smoothxg (1) [ 50%] 1 of 2
[-        ] process > odgiBuild    -
[-        ] process > odgiStats    -
[-        ] process > odgiViz      -
[-        ] process > odgiChop     -
[-        ] process > odgiLayout   -
[-        ] process > odgiDraw     -
Execution cancelled -- Finishing pending tasks before exit
Error executing process > 'odgiBuild (1)'

Caused by:
  Process `odgiBuild` input file name collision -- There are multiple input files for each of the following file names: ncbi200.pggb-s1000-p90-n10-a90-K16-X-k8-w10000-j5000-W0-e5000-I0.seqwish.gfa


Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
```
## Expected behaviour

to continue pipeline

## Log files

Have you provided the following extra information/files:
log was deleted

## System

- Hardware: AWS c5a.8xlarge
- Executor: 
- OS: Ubuntu 20.04
- Version 

## Nextflow Installation

- Version: 20.10.0

## Container engine

- Engine: Docker
- version: Docker version 19.03.13, build cd8016b6bc
- Image tag: dev

## Additional context
Pipeline proceeded to next stage when files were renamed to following:
```bash
788K -rw-rw-r--  1 ubuntu ubuntu 785K Feb 21 17:12 ncbi200_01.fasta.gz
784K -rw-rw-r--  1 ubuntu ubuntu 783K Feb 21 17:12 ncbi200_00.fasta.gz```

**Comment by subwaystation** [comment] 2021-02-22 09:37
Hi @dbrami 
`pangenome` can't handle a list of input FASTAs, yet. See #39 and #37.
 I would mark this as a duplicate of #39. 
 
 Let's leave it open until I resolved this.

**Comment by dbrami** [comment] 2021-02-22 12:11
Apologies for the double post - I'm losing my marbles with a one year old
baby that never sleeps...

**Comment by subwaystation** [comment] 2021-03-02 13:19
This is already tracked in #39

**Closed by subwaystation** 2021-03-02 13:19 UTC
Labels: bug
